### ISSUE TITLE
无法连接ssh

### ISSUE THREAD

**Issue by dmmdekkd** [lollipopkit/flutter_server_box#627]
**描述BUG**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**设备**

**更多信息**

SftpStatusError: No such file(code 2)
#0      SftpClient._opendir (package:dartssh2/src/sftp/sftp_client.dart:198)
<asynchronous suspension>
#1      SftpClient.readdir (package:dartssh2/src/sftp/sftp_client.dart:77)
<asynchronous suspension>
#2      SftpClient.listdir (package:dartssh2/src/sftp/sftp_client.dart:90)
<asynchronous suspension>
#3      _SftpPageState._listDir.<anonymous closure> (package:server_box/view/page/storage/sftp.dart:599)
<asynchronous suspension>
#4      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:963)
<asynchronous suspension>
#5      DialogX.showLoadingDialog.<anonymous closure> (package:fl_lib/src/core/ext/ctx/dialog.dart:67)
<asynchronous suspension>
#6      Resx.tryCatch (package:fl_lib/src/model/result.dart:34)
<asynchronous suspension>
#7      _SftpPageState._listDir (package:server_box/view/page/storage/sftp.dart:595)
<asynchronous suspension>

**Comment by GT-610** [comment]
`No such file or directory`的问题应该在v1296及之后的版本中修复。试试最新版本，如果还有问题请开新的issue，谢谢。
