### ISSUE TITLE
Unable to access via sftp

### ISSUE THREAD

**Issue by firestarter7924** [lollipopkit/flutter_server_box#628]
Hello! First, big thank you for you great job. This app is awesome.
Have a strange bug. There are 3 servers in app and only 1 server is strange. 
This is bug log. It's when I try to access via sftp.
SftpStatusError: No such file(code 2)
#0      SftpClient._opendir (package:dartssh2/src/sftp/sftp_client.dart:198)
<asynchronous suspension>
#1      SftpClient.readdir (package:dartssh2/src/sftp/sftp_client.dart:77)
<asynchronous suspension>
#2      SftpClient.listdir (package:dartssh2/src/sftp/sftp_client.dart:90)
<asynchronous suspension>
#3      _SftpPageState._listDir.<anonymous closure> (package:server_box/view/page/storage/sftp.dart:608)
<asynchronous suspension>
#4      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:963)
<asynchronous suspension>
#5      DialogX.showLoadingDialog.<anonymous closure> (package:fl_lib/src/core/ext/ctx/dialog.dart:67)
<asynchronous suspension>
#6      Resx.tryCatch (package:fl_lib/src/model/result.dart:34)
<asynchronous suspension>
#7      _SftpPageState._listDir (package:server_box/view/page/storage/sftp.dart:604)
<asynchronous suspension>

**Comment by GT-610** [comment]
Latest version fixed issues related to SFTP. Please check if these bugs still exist. If so, please open a new issue. Thanks!
