### ISSUE TITLE
打开底栏ssh连接服务器闪退

### ISSUE THREAD

**Issue by baizice** [lollipopkit/flutter_server_box#636]
复现方法：启动app后直接ssh页面开ssh
![Screenshot_20241119-165131_设置](https://github.com/user-attachments/assets/f386b42a-4d93-4821-83eb-2e9f3fc90a17)

FATAL EXCEPTION: main
Process: tech.lolli.toolbox, PID: 16062
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4a75da5 u0 tech.lolli.toolbox/.ForegroundService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2130)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2101)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2395)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

**Comment by KleeSky** [comment]
+1

**Comment by baizice** [comment]
通知权限给了
从服务器菜单里面ssh可以正常连接

**Comment by lollipopkit** [comment]
Fixed in #658
