### ISSUE TITLE
Crash while opening terminal

### ISSUE THREAD

**Issue by ekyfig** [lollipopkit/flutter_server_box#639]
**Describe the bug**

when try to open a terminal,the app crashes

**To Reproduce**

**Desired Results**

**Actual Results**

**Screenshots**

**Device**

**Additional context**

**Comment by ekyfig** [comment]
here is log:
FATAL EXCEPTION: main
Process: tech.lolli.toolbox, PID: 1406
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{89830c0 u0 tech.lolli.toolbox/.ForegroundService c:tech.lolli.toolbox}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2271)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2239)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2557)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8700)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by nholben** [comment]
Issue happens to me as well. If I open the server tab and go into my selected server I can connect it SSH via the tab at the top. However, clicking the SSH tab at the bottom then clicking on my selected server the app immediately crashes.

**Comment by silvernode** [comment]
I reverted because of this issue so very it is 100% reproducible. It will not crash on first launch but once you get some cache it will crash every time after that. Clearing cache allows the app not to crash once but only once. So then you gotta clear the cache to access it from the global terminals panel once again. Rinse and repeat.

Hope it gets fixed soon so I can update to the latest version. Thank you for this fantastic program.

**Comment by lollipopkit** [comment]
Due to this bug, the foreground service feature will be removed in 2f6db29.

This will be pinned, hope anyone can fix it.
